# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # macOS Sonoma, has newer Xcode versions

    steps:
    - name: Select Xcode 15.4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    - uses: actions/checkout@v4

    - name: Build
      run: xcodebuild build -scheme d2d-map-service -destination 'platform=iOS Simulator,name=iPhone 16'
